variables: 
  BIBSERVERURL: "https://api.bibify.org"
  AWS_DEFAULT_REGION: us-west-1
stages:
  - test
  - build
  - deploy
test build:
  stage: test
  image: node:latest
  script:
  - npm i
  - npm run build

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.15.0
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
    - master

deploy to s3:
  stage: deploy
  image: node:latest
  script:
    - npm i
    - npm run build
    - apt update
    - apt install python3-pip
    - pip3 install awscli
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME/ --recursive 
  only:
    - tags
    - master
